### ISSUE TITLE
maximum reference limited

### ISSUE THREAD

**Issue by huangziyan11111** [mahulchak/quickmerge#30]
I run this command:/psd/biosoft/quickmerge/merge_wrapper.py -pre test_canu -hco 5.0 -c 1.5 -l 310000 -lm 7000 DBG2OLC.fasta canu.sub.fasta
while I got an error about the maximum reference:
###############################################
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "test_canu.ntref" of length 1107738543
# construct suffix tree for sequence of length 1107738543
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 11077385 characters per dot
/psd/biosoft/MUMmer3.23/mummer: suffix tree construction failed: textlen=1107738543 larger than maximal textlen=536870908
ERROR: mummer and/or mgaps returned non-zero
ERROR: Could not parse delta file, test_canu.delta
error no: 400
Traceback (most recent call last):
  File "/psd/biosoft/quickmerge/merge_wrapper.py", line 174, in <module>
    subprocess.call(mergercall)
  File "/usr/local/Python-2.7.9/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Python-2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Python-2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
###############################################

How can I solve this error? Increasing the maximum reference length? And how to do?
Thank you for your attention.

**Comment by esolares** [comment]
Hi

Thank you for your email. Have you tried to run it without the wrapper?

**Comment by mahulchak** [comment]
I think the error is because of MUMmer. Your assembly is too large for it.
I think you will either have to compile a 64 bit MUMmer v3 or use MUMmer v4.
